name: Build
on: [push]

env:
  MINIKUBE_VERSION: v1.25.2
  DOCKER_IMAGE_TAG: latest-1.21
  KUBERNETES_VERSION: v1.21.1
  DOCKER_IMAGE: 20-dind

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the image 
        run: ./build.sh ${{ secrets.DOCKERHUB_USERNAME }}/kind:${DOCKER_IMAGE_TAG} ${{ secrets.DOCKERHUB_USERNAME }}/kind:${KUBERNETES_VERSION}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Tag the Docker when not master
        if: github.ref != 'refs/heads/master'
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/kind:${DOCKER_IMAGE_TAG} ${{ secrets.DOCKERHUB_USERNAME }}/kind:${DOCKER_IMAGE_TAG}.${{ steps.date.outputs.date }}

      - name: Docker Push when not master
        if: github.ref != 'refs/heads/master'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kind:${DOCKER_IMAGE_TAG}.${{ steps.date.outputs.date }}

      - name: Docker Push when master
        if: github.ref == 'refs/heads/master'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kind:${DOCKER_IMAGE_TAG}