name: Build
on: [push]

env:
  MINIKUBE_VERSION: v1.15.1
  DOCKER_IMAGE_TAG: latest-1.21
  KUBERNETES_VERSION: v1.21.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the image 
        run: /build.sh bsycorp/kind:${DOCKER_IMAGE_TAG} bsycorp/kind:${KUBERNETES_VERSION}